### ISSUE TITLE
consider loco.rs

### ISSUE THREAD

**Issue by jondot** [danielclough/fireside-chat#2]
Hi Daniel,
Thanks for referring me to your example using LLMs, I wanted to point you to `loco.rs`, a kind of "rust on rails" framework to set up your server with: https://loco.rs

From looking at your codebase, I feel it can save you quite a bit of typing + give you a lot of extras + set you up for success as the project evolves (for example you get a database layer integrated, and JWT authentication for free)

**Comment by danielclough** [comment]
@jondot 
Thanks for the suggestion!
I'm getting a 404 on that link though.

I did find the github, so I can check it out later.

**Comment by jondot** [comment]
It is back up now :)

**Comment by danielclough** [comment]
I think I'm going to keep the backend light on dependencies.

Loco does look pretty convenient though, so maybe I will make time to make a play project to experiment with it.

Good luck!
